version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python-minor-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 0  # don't have the bandwidth for right now. putting this in place now for security PRs.

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 0  # don't have the bandwidth for right now. putting this in place now for security PRs.

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0  # don't have the bandwidth for right now. putting this in place now for security PRs.

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0  # don't have the bandwidth for right now. putting this in place now for security PRs.
