"""End-to-end tests for the Sheaf archive (export-with-images zip) runner.

The archive importer wraps the native JSON walk with blob restore:
referenced images are re-uploaded through the shared normalize/quota
pipeline and references rewritten to the new keys. These tests build
small zips inline (export.json + images/<key>) and assert on the
restored rows, the UploadedFile accounting via /v1/files/list, and the
failure paths (cap precheck before any blob lands, zip guards,
missing-blob warnings, re-import discard).
"""

from __future__ import annotations

import io
import json
import uuid
import zipfile

import httpx

from tests._import_runner_helpers import (
    drive_import_runner,
    set_member_limit,
    wait_for_terminal,
)

# 4x4 RGBA PNG generated by Pillow. Survives a real decode pass through
# normalize_image (hand-written IDAT smuggling blobs don't).
_TINY_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x04\x00\x00\x00\x04"
    b"\x08\x06\x00\x00\x00\xa9\xf1\x9e~\x00\x00\x00\x15IDATx\x9cc\xfc\xcf"
    b"\xc0\xf0\x9f\x01\t01\xa0\x01\xc2\x02\x00\x83\xd1\x02\x06\x02\x90\xef"
    b"X\x00\x00\x00\x00IEND\xaeB`\x82"
)

# Keys deliberately under a foreign owner id: the importer must mint
# fresh keys under the importing user, never reuse these.
_AVATAR_KEY = "avatars/00000000-0000-0000-0000-00000000aaaa/oldavatar.png"
_EMBED_KEY = "avatars/00000000-0000-0000-0000-00000000aaaa/oldembed.png"


def _sample_export(
    *,
    avatar_key: str = _AVATAR_KEY,
    embed_key: str = _EMBED_KEY,
    with_journal: bool = True,
) -> dict:
    return {
        "version": "2",
        "system": {"name": "Archive System"},
        "members": [
            {
                "id": "m1",
                "name": "ArcIris",
                "avatar_url": avatar_key,
                "description": f"hello ![pic](/v1/files/{embed_key}) world",
            },
            {"id": "m2", "name": "ArcJay"},
        ],
        "fronts": [],
        "groups": [],
        "tags": [],
        "custom_fields": [],
        "journals": (
            [
                {
                    "id": "j1",
                    "title": "with embed",
                    "body": f"entry ![pic](/v1/files/{embed_key})",
                    "image_keys": [embed_key],
                }
            ]
            if with_journal
            else []
        ),
    }


def _make_archive(
    data: dict, images: dict[str, bytes] | None = None
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("export.json", json.dumps(data))
        zf.writestr("README.txt", "test archive")
        for key, blob in (images or {}).items():
            zf.writestr(f"images/{key}", blob)
    return buf.getvalue()


def _default_images() -> dict[str, bytes]:
    return {_AVATAR_KEY: _TINY_PNG, _EMBED_KEY: _TINY_PNG}


def _post_archive(
    client: httpx.Client,
    payload: bytes,
    *,
    options: dict | None = None,
) -> dict:
    form: dict[str, str] = {
        "source": "sheaf_archive",
        "idempotency_key": str(uuid.uuid4()),
    }
    if options is not None:
        form["options"] = json.dumps(options)
    resp = client.post(
        "/v1/imports/file",
        files={"file": ("sheaf.zip", payload, "application/zip")},
        data=form,
    )
    assert resp.status_code == 202, resp.text
    return resp.json()


def _files_list(client: httpx.Client) -> list[dict]:
    resp = client.get("/v1/files/list")
    assert resp.status_code == 200, resp.text
    return resp.json()


# --- Happy path --------------------------------------------------------------


def test_archive_restores_avatars_and_embeds(auth_client: httpx.Client):
    """Avatar, markdown embed, and journal image_keys all come back
    pointing at freshly-minted keys owned by the importing user."""
    job = _post_archive(auth_client, _make_archive(_sample_export(), _default_images()))
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["members_imported"] == 2, final["counts"]
    assert final["counts"]["images_imported"] == 2, final["counts"]

    files = _files_list(auth_client)
    file_keys = {f["key"] for f in files}
    assert len(files) == 2, files
    # Fresh keys under the importing user, never the foreign originals.
    assert _AVATAR_KEY not in file_keys
    assert _EMBED_KEY not in file_keys

    members = auth_client.get("/v1/members").json()
    iris = next(m for m in members if m["name"] == "ArcIris")
    # MemberRead serialises avatar_url through the serve-path resolver,
    # so compare on the key behind it.
    avatar_key = (iris["avatar_url"] or "").removeprefix("/v1/files/")
    assert avatar_key in file_keys, iris["avatar_url"]
    # The embed in the bio is rewritten to the canonical serve path of a
    # new key (and the old key is gone from the text).
    assert _EMBED_KEY not in (iris["description"] or "")
    assert any(
        f"/v1/files/{k}" in (iris["description"] or "") for k in file_keys
    ), iris["description"]


def test_archive_images_toggle_off_behaves_like_json_import(
    auth_client: httpx.Client,
):
    """images=false strips internal refs exactly like the plain import."""
    job = _post_archive(
        auth_client,
        _make_archive(_sample_export(), _default_images()),
        options={"images": False},
    )
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"].get("images_imported", 0) == 0, final["counts"]
    assert _files_list(auth_client) == []

    members = auth_client.get("/v1/members").json()
    iris = next(m for m in members if m["name"] == "ArcIris")
    assert iris["avatar_url"] is None, iris
    assert "/v1/files/" not in (iris["description"] or "")


def test_archive_missing_blob_strips_with_warning(auth_client: httpx.Client):
    """A referenced key absent from images/ degrades to the strip
    behaviour with a user-facing warning, not a failure."""
    job = _post_archive(
        auth_client,
        # Only the embed blob is bundled; the avatar blob is missing.
        _make_archive(_sample_export(), {_EMBED_KEY: _TINY_PNG}),
    )
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["images_imported"] == 1, final["counts"]
    # One warning event per missing key, carrying the storage key as
    # record_ref and naming the referencing records (by export-side id)
    # in the message - "what did I actually lose?" is answerable from
    # the import report.
    missing_events = [
        e
        for e in final["events"]
        if e["level"] == "warning" and "missing from the archive" in e["message"]
    ]
    assert len(missing_events) == 1, final["events"]
    assert missing_events[0]["record_ref"] == _AVATAR_KEY, missing_events
    assert "member m1 avatar" in missing_events[0]["message"], missing_events

    members = auth_client.get("/v1/members").json()
    iris = next(m for m in members if m["name"] == "ArcIris")
    assert iris["avatar_url"] is None, iris


# --- Failure paths -----------------------------------------------------------


def test_archive_member_cap_fails_before_any_blob(auth_client: httpx.Client):
    """The cap precheck runs before any storage write: a failed job
    leaves zero uploaded files behind."""
    set_member_limit(auth_client, 1)
    job = _post_archive(auth_client, _make_archive(_sample_export(), _default_images()))
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any("limited to" in e["message"] for e in final["events"]), final["events"]
    assert auth_client.get("/v1/members").json() == []
    assert _files_list(auth_client) == []


def test_archive_rejects_garbage_zip(auth_client: httpx.Client):
    job = _post_archive(auth_client, b"PK\x03\x04 this is not really a zip")
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any(
        "not a valid zip archive" in e["message"] for e in final["events"]
    ), final["events"]


def test_archive_rejects_zip_without_export_json(auth_client: httpx.Client):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("data.json", "{}")
    job = _post_archive(auth_client, buf.getvalue())
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any(
        "must contain export.json" in e["message"] for e in final["events"]
    ), final["events"]


def test_archive_rejects_decompression_bomb(auth_client: httpx.Client):
    """export.json declaring a decompressed size over the cap is refused
    before any JSON parse happens."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # 260MB of spaces compresses to almost nothing but declares its
        # true size in the entry header, which is what the guard reads.
        zf.writestr("export.json", b" " * (260 * 1024 * 1024))
    job = _post_archive(auth_client, buf.getvalue())
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any(
        "decompresses to more than" in e["message"] for e in final["events"]
    ), final["events"]


# --- Re-import / dedup interplay ---------------------------------------------


def test_archive_reimport_discards_unused_uploads(auth_client: httpx.Client):
    """Re-importing the same archive dedups the members (skip default),
    so the freshly-uploaded blobs end up unreferenced and are discarded:
    storage usage must not grow.

    Journal-free export: journals are appended (not deduped) on
    re-import, so a bundled journal embed would be a legitimate re-use
    of the blob and the second run would rightly keep it.
    """
    export = _sample_export(with_journal=False)
    first = _post_archive(auth_client, _make_archive(export, _default_images()))
    drive_import_runner()
    assert wait_for_terminal(auth_client, first["id"])["status"] == "complete"
    files_after_first = {f["key"] for f in _files_list(auth_client)}
    assert len(files_after_first) == 2

    second = _post_archive(auth_client, _make_archive(export, _default_images()))
    drive_import_runner()
    final = wait_for_terminal(auth_client, second["id"])

    assert final["status"] == "complete", final
    assert final["counts"].get("members_skipped", 0) == 2, final["counts"]
    assert final["counts"].get("images_imported", 0) == 0, final["counts"]

    files_after_second = {f["key"] for f in _files_list(auth_client)}
    assert files_after_second == files_after_first, files_after_second
