"""End-to-end tests for the PluralSpace import runner.

Builds the export zip inline with sanitised data — the importer
mirrors a `format_version: "1.1"` shape captured from a real
PluralSpace export. Tests cover the runner plumbing, the
preview endpoint, and a handful of mapping decisions worth
locking in:
- Multi-channel chat collapse with channel-name prefix on each
  message body.
- `closes_at: null` polls default to a one-year close window
  with a warning event.
- `thoughts[]` is unsupported and surfaces a warning.
- Roles are imported as tags by default.
"""

from __future__ import annotations

import io
import json
import uuid
import zipfile

import httpx

from tests._import_runner_helpers import (
    drive_import_runner,
    wait_for_terminal,
)

# 4x4 RGBA PNG generated by Pillow. The PNG header smuggling tricks
# used elsewhere on the wire have hand-written IDAT chunks that don't
# survive a real decode pass through normalize_image; this one does.
_TINY_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x04\x00\x00\x00\x04"
    b"\x08\x06\x00\x00\x00\xa9\xf1\x9e~\x00\x00\x00\x15IDATx\x9cc\xfc\xcf"
    b"\xc0\xf0\x9f\x01\t01\xa0\x01\xc2\x02\x00\x83\xd1\x02\x06\x02\x90\xef"
    b"X\x00\x00\x00\x00IEND\xaeB`\x82"
)


def _sample_data(
    *,
    chat_channel_count: int = 1,
    thoughts: bool = False,
    poll_open_ended: bool = False,
    with_avatar: bool = False,
) -> dict:
    """Build a sanitised PluralSpace data.json payload.

    Tests tweak the kwargs to exercise individual mapping decisions
    without rebuilding the whole structure each time.
    """
    member_a = str(uuid.uuid4())
    member_b = str(uuid.uuid4())
    channels = [
        {
            "id": str(uuid.uuid4()),
            "name": f"channel-{i}",
            "created_at": "2026-06-08T00:08:28+00:00",
            "messages": [
                {
                    "id": str(uuid.uuid4()),
                    "member_name": "Alpha",
                    "content": f"hello from channel {i}",
                    "created_at": "2026-06-08T00:13:09+00:00",
                }
            ],
        }
        for i in range(chat_channel_count)
    ]
    return {
        "system": {
            "name": "Test System",
            "slug": "test-system",
            "description": "imported under test",
            "color": "#7c3aed",
            "visibility": "private",
            "created_at": "2026-06-04T07:52:07+00:00",
        },
        "members": [
            {
                "id": member_a,
                "name": "Alpha",
                "display_name": "A",
                "pronouns": "they/them",
                "description": "alpha bio",
                "color": "#f472b6",
                "role": ["protector", "host"],
                "is_archived": False,
                "is_custom_front": False,
                "avatar_path": None,
                "avatar_media_path": (
                    "media/member-avatar-alpha.png" if with_avatar else None
                ),
                "groups": ["protectors"],
                "custom_field_values": [
                    {"field_name": "Likes", "value": "lasers"},
                    {"field_name": "Likes", "value": "LEDs"},
                    {"field_name": "Birthday", "value": "1970-01-01"},
                ],
                "created_at": "2026-06-08T00:10:59+00:00",
            },
            {
                "id": member_b,
                "name": "Beta",
                "display_name": None,
                "pronouns": "she/her",
                "description": "beta bio",
                "color": "#94a3b8",
                "role": ["protector"],
                "is_archived": False,
                "is_custom_front": False,
                "avatar_path": None,
                "avatar_media_path": None,
                "groups": ["protectors"],
                "custom_field_values": [],
                "created_at": "2026-06-08T00:15:23+00:00",
            },
        ],
        "fronts": [
            {
                "id": str(uuid.uuid4()),
                "member_id": member_a,
                "member_name": "Alpha",
                "type": "front",
                "type_name": "Front",
                "started_at": "2026-06-08T00:11:11+00:00",
                "ended_at": None,
                "comment": "live",
                "is_live": True,
            }
        ],
        "journal_entries": [
            {
                "id": str(uuid.uuid4()),
                "title": "co-authored",
                "content": "multi-member journal entry",
                "visibility_level": 3,
                "members": [
                    {"id": member_a, "name": "Alpha"},
                    {"id": member_b, "name": "Beta"},
                ],
                "date": "2026-06-08T00:22:00+00:00",
                "created_at": "2026-06-08T00:23:20+00:00",
                "updated_at": "2026-06-08T00:23:20+00:00",
            }
        ],
        "chat_channels": channels,
        "polls": [
            {
                "id": str(uuid.uuid4()),
                "title": "open question",
                "description": "a sample poll",
                "status": "open",
                "allows_multiple_votes": True,
                "created_by_member": {"id": member_b, "name": "Beta"},
                "closes_at": None if poll_open_ended else "2027-01-01T00:00:00+00:00",
                "created_at": "2026-06-08T00:26:41+00:00",
                "options": [
                    {
                        "id": str(uuid.uuid4()),
                        "text": "yes",
                        "vote_count": 1,
                        "votes": [
                            {
                                "member_name": "Alpha",
                                "created_at": "2026-06-08T00:26:46+00:00",
                            }
                        ],
                    },
                    {
                        "id": str(uuid.uuid4()),
                        "text": "no",
                        "vote_count": 0,
                        "votes": [],
                    },
                ],
            }
        ],
        "thoughts": (
            [{"id": str(uuid.uuid4()), "content": "thought one"}] if thoughts else []
        ),
        "member_groups": [
            {
                "id": str(uuid.uuid4()),
                "name": "protectors",
                "color": "#94a3b8",
                "description": "we do the protecting.",
                "members": [
                    {"id": member_a, "name": "Alpha"},
                    {"id": member_b, "name": "Beta"},
                ],
                "created_at": "2026-06-08T00:31:33+00:00",
            }
        ],
        "custom_fields": [
            {
                "id": str(uuid.uuid4()),
                "name": "Likes",
                "field_type": "text",
                "is_multiple": True,
                "values": [
                    {"member_name": "Alpha", "value": "lasers"},
                    {"member_name": "Alpha", "value": "LEDs"},
                ],
            },
            {
                "id": str(uuid.uuid4()),
                "name": "Birthday",
                "field_type": "date",
                "is_multiple": False,
                "values": [
                    {"member_name": "Alpha", "value": "1970-01-01"},
                ],
            },
        ],
        "media_files": (
            ["media/member-avatar-alpha.png"] if with_avatar else []
        ),
    }


def _build_zip(
    data: dict,
    *,
    include_manifest: bool = True,
    include_data: bool = True,
    media: dict[str, bytes] | None = None,
) -> bytes:
    """Pack the data + manifest into a PluralSpace-shape zip in memory."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        if include_manifest:
            zf.writestr(
                "manifest.json",
                json.dumps(
                    {
                        "export_date": "2026-06-08T00:33:32+00:00",
                        "system_name": data.get("system", {}).get("name", ""),
                        "format_version": "1.1",
                        "user_email": "tester@example.invalid",
                        "regulation_reference": "GDPR Article 15 / 20",
                    }
                ),
            )
        if include_data:
            zf.writestr("data.json", json.dumps(data))
        for path, blob in (media or {}).items():
            zf.writestr(path, blob)
    return buf.getvalue()


def _post_file(
    client: httpx.Client,
    payload: bytes,
    *,
    idem_key: str | None = None,
    options: dict | None = None,
) -> dict:
    form: dict[str, str] = {
        "source": "pluralspace_file",
        "idempotency_key": idem_key or str(uuid.uuid4()),
    }
    if options is not None:
        form["options"] = json.dumps(options)
    resp = client.post(
        "/v1/imports/file",
        files={"file": ("export.zip", payload, "application/zip")},
        data=form,
    )
    assert resp.status_code == 202, resp.text
    return resp.json()


# --- Preview --------------------------------------------------------------


def test_preview_returns_summary(auth_client: httpx.Client):
    payload = _build_zip(_sample_data())
    resp = auth_client.post(
        "/v1/import/pluralspace/preview",
        files={"file": ("export.zip", payload, "application/zip")},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["member_count"] == 2
    assert body["format_version"] == "1.1"
    assert body["poll_count"] == 1
    names = {m["name"] for m in body["members"]}
    assert names == {"Alpha", "Beta"}


def test_preview_rejects_non_zip(auth_client: httpx.Client):
    resp = auth_client.post(
        "/v1/import/pluralspace/preview",
        files={"file": ("export.zip", b"not a zip", "application/zip")},
    )
    assert resp.status_code == 400


def test_preview_rejects_missing_manifest(auth_client: httpx.Client):
    payload = _build_zip(_sample_data(), include_manifest=False)
    resp = auth_client.post(
        "/v1/import/pluralspace/preview",
        files={"file": ("export.zip", payload, "application/zip")},
    )
    assert resp.status_code == 400


# --- Runner ---------------------------------------------------------------


def test_runner_imports_members_and_attaches_role_tags(auth_client: httpx.Client):
    job = _post_file(auth_client, _build_zip(_sample_data()))
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["members_imported"] == 2, final["counts"]
    # "protector" + "host" -> 2 distinct tags
    assert final["counts"]["tags_imported"] == 2, final["counts"]

    members = auth_client.get("/v1/members").json()
    by_name = {m["name"]: m for m in members}
    assert {"Alpha", "Beta"}.issubset(by_name.keys())

    alpha_tags = auth_client.get(f"/v1/members/{by_name['Alpha']['id']}/tags").json()
    tag_names = {t["name"] for t in alpha_tags}
    assert {"protector", "host"} == tag_names


def test_runner_fronts_and_groups(auth_client: httpx.Client):
    job = _post_file(auth_client, _build_zip(_sample_data()))
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["fronts_imported"] == 1
    assert final["counts"]["groups_imported"] == 1


def test_runner_multi_channel_chat_collapses_with_prefix(auth_client: httpx.Client):
    job = _post_file(
        auth_client, _build_zip(_sample_data(chat_channel_count=2))
    )
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["messages_imported"] == 2
    assert any(
        "channels" in e["message"].lower() and e["level"] == "warning"
        for e in final["events"]
    ), final["events"]


def test_runner_open_ended_poll_gets_one_year_window(auth_client: httpx.Client):
    job = _post_file(
        auth_client, _build_zip(_sample_data(poll_open_ended=True))
    )
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"]["polls_imported"] == 1
    assert any(
        "close time" in e["message"].lower() and e["level"] == "warning"
        for e in final["events"]
    ), final["events"]


def test_runner_thoughts_surface_warning(auth_client: httpx.Client):
    job = _post_file(auth_client, _build_zip(_sample_data(thoughts=True)))
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert any(
        "thought" in e["message"].lower() and e["level"] == "warning"
        for e in final["events"]
    ), final["events"]


def test_runner_member_avatar_uploaded(auth_client: httpx.Client):
    payload = _build_zip(
        _sample_data(with_avatar=True),
        media={"media/member-avatar-alpha.png": _TINY_PNG},
    )
    job = _post_file(auth_client, payload)
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "complete", final
    assert final["counts"].get("avatars_imported", 0) == 1, final["counts"]


def test_runner_fails_on_bad_zip(auth_client: httpx.Client):
    job = _post_file(auth_client, b"definitely not a zip")
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any(
        "zip" in e["message"].lower() and e["level"] == "error"
        for e in final["events"]
    ), final["events"]


def test_runner_fails_when_data_json_missing(auth_client: httpx.Client):
    payload = _build_zip(_sample_data(), include_data=False)
    job = _post_file(auth_client, payload)
    drive_import_runner()
    final = wait_for_terminal(auth_client, job["id"])

    assert final["status"] == "failed", final
    assert any(
        "data.json" in e["message"] for e in final["events"]
    ), final["events"]
