"""Add account status, email verification, and invite codes

Revision ID: 105395daaa47
Revises: 5137a5094b37
Create Date: 2026-03-26 10:11:19.828747
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105395daaa47'
down_revision: Union[str, None] = '5137a5094b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    accountstatus = sa.Enum('active', 'pending_approval', 'suspended', 'banned', 'pending_deletion', name='accountstatus')
    accountstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('account_status', accountstatus, server_default='active', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # Existing users predate verification — mark them as verified
    op.execute("UPDATE users SET email_verified = true")
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'account_status')
    sa.Enum(name='accountstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
